In [1]:
import numpy as np
x = np.arange(10)

In [2]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [5]:
x[::3]

array([0, 3, 6, 9])

In [6]:
x[1::2] # every other element starting at index 1

array([1, 3, 5, 7, 9])

In [7]:
x[::-1] # all elemens are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

# multi dimensional Sub arrays

In [10]:
import numpy as np
np.random.seed(40)
x2 = np.random.randint(10, size  = (3,4))

In [11]:
x2

array([[6, 7, 5, 8],
       [8, 2, 1, 7],
       [2, 3, 7, 3]])

In [13]:
x2[:2,:3] # 2 rows ,3 columns

array([[6, 7, 5],
       [8, 2, 1]])

In [14]:
x2[:3,::2] # all rows and every other column

array([[6, 5],
       [8, 1],
       [2, 7]])

In [16]:
x2

array([[6, 7, 5, 8],
       [8, 2, 1, 7],
       [2, 3, 7, 3]])

In [15]:
# reverse of sub arrays
x2[::-1,::-1]

array([[3, 7, 3, 2],
       [7, 1, 2, 8],
       [8, 5, 7, 6]])

# accesing array rows and columns

In [ ]:
# Subarrays as no-copy views
# One important—and extremely useful—thing to know about array slices is that they
# return views rather than copies of the array data. This is one area in which NumPy
# array slicing differs from Python list slicing: in lists, slices will be copies. Consider our
# two-dimensional array from before:

In [17]:
x2

array([[6, 7, 5, 8],
       [8, 2, 1, 7],
       [2, 3, 7, 3]])

In [22]:
# first column  all rows
x2[:,0]

array([6, 8, 2])

In [23]:
# first row and cplumns
x2[0,:]

array([6, 7, 5, 8])

In [24]:
x2

array([[6, 7, 5, 8],
       [8, 2, 1, 7],
       [2, 3, 7, 3]])

In [25]:
# 2 rows with 2 columns
x2[:2,:2]

array([[6, 7],
       [8, 2]])

In [ ]:
# Now if we modify this subarray, we’ll see that the original array is changed! Observe:

In [26]:
x2[0,0] = 99

In [27]:
x2[:2,:2]

array([[99,  7],
       [ 8,  2]])

# creating copies of arrays

In [ ]:
# it is sometimes useful to instead explicitly
# copy the data within an array or a subarray. This can be most easily done with the
# copy() method:

In [28]:
x2

array([[99,  7,  5,  8],
       [ 8,  2,  1,  7],
       [ 2,  3,  7,  3]])

In [29]:
sub_array = x2[:2,:2].copy()

In [30]:
sub_array

array([[99,  7],
       [ 8,  2]])

In [31]:
sub_array[0,0] = 40

In [32]:
sub_array

array([[40,  7],
       [ 8,  2]])

In [34]:
x2[:2,:2]

array([[99,  7],
       [ 8,  2]])