In [ ]:
# source :
# https://www.youtube.com/watch?v=4HKqjENq9OU&list=PLEiEAq2VkUULYYgj13YHUWmRePqiu8Ddy&index=20

In [ ]:
# KNN = k nearest neighbors , is one of the supervised algorithm majorly used for classification

In [ ]:
# knn stores all available cases and classifies new cases based on a similarity measure

In [ ]:
# K in knn is a parameter that refers to the number of nearest neighbors to include in the
#                                            majority voting process

# how to choose K

In [ ]:
# odd value of k is selected to avoid confusion between two classes of data

# when we use knn

In [ ]:
# when dataset is small
# when data is labelled
# when data is noise free

# importing required packages

In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
%matplotlib inline

In [69]:
dataset = pd.read_csv("C:\d disk\machine learning\diabetes.csv")

In [70]:
len(dataset)

768

In [71]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [43]:
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [72]:
dataset.shape

(768, 9)

In [ ]:
# values of columns like 'glucose' , ' blood pressure' cannot be accepted as zeroes and 0 values 
#           are replaced with mean of respective column

In [73]:
# replace zeroes
zero_not_accepted = ['Glucose','BloodPressure','SkinThickness','BMI','Insulin']
for column in zero_not_accepted:
    dataset[column] = dataset[column].replace(0,np.NaN) # NaN means no data
    mean = int(dataset[column].mean(skipna=True))
    dataset[column] = dataset[column].replace(np.NaN,mean)
    

In [74]:
print(dataset['SkinThickness'])

0      35.0
1      29.0
2      29.0
3      23.0
4      35.0
5      29.0
6      32.0
7      29.0
8      45.0
9      29.0
10     29.0
11     29.0
12     29.0
13     23.0
14     19.0
15     29.0
16     47.0
17     29.0
18     38.0
19     30.0
20     41.0
21     29.0
22     29.0
23     35.0
24     33.0
25     26.0
26     29.0
27     15.0
28     19.0
29     29.0
       ... 
738    17.0
739    29.0
740    37.0
741    20.0
742    18.0
743    29.0
744    37.0
745    33.0
746    41.0
747    41.0
748    22.0
749    29.0
750    29.0
751    39.0
752    24.0
753    44.0
754    32.0
755    39.0
756    41.0
757    29.0
758    29.0
759    29.0
760    26.0
761    31.0
762    29.0
763    48.0
764    27.0
765    23.0
766    29.0
767    31.0
Name: SkinThickness, Length: 768, dtype: float64


# now split the data into train and test

In [75]:
#split dataset
X = dataset.iloc[:,0:8] # this indicates in pandas all rows and columns from 0 to 8 
y = dataset.iloc[:,8]   # all rows and only single 8 column
X_train , X_test , y_train , y_test = train_test_split(X,y,random_state = 0 ,test_size =0.2)

In [12]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
603            7    150.0           78.0           29.0    126.0  35.2   
118            4     97.0           60.0           23.0    155.0  28.2   
247            0    165.0           90.0           33.0    680.0  52.3   
157            1    109.0           56.0           21.0    135.0  25.2   
468            8    120.0           72.0           29.0    155.0  30.0   
193           11    135.0           72.0           29.0    155.0  52.3   
306           10    161.0           68.0           23.0    132.0  25.5   
319            6    194.0           78.0           29.0    155.0  23.5   
97             1     71.0           48.0           18.0     76.0  20.4   
530            2    122.0           60.0           18.0    106.0  29.8   
327           10    179.0           70.0           29.0    155.0  35.1   
619            0    119.0           72.0           29.0    155.0  32.4   
518           13     76.0           60.0           29.0    155.0  32.8   
632            2    111.0           60.0           29.0    155.0  26.2   
524            3    125.0           58.0           29.0    155.0  31.6   
536            0    105.0           90.0           29.0    155.0  29.6   
597            1     89.0           24.0           19.0     25.0  27.8   
462            8     74.0           70.0           40.0     49.0  35.3   
17             7    107.0           74.0           29.0    155.0  29.6   
739            1    102.0           74.0           29.0    155.0  39.5   
263            3    142.0           80.0           15.0    155.0  32.4   
241            4     91.0           70.0           32.0     88.0  33.1   
344            8     95.0           72.0           29.0    155.0  36.8   
302            5     77.0           82.0           41.0     42.0  35.8   
704            4    110.0           76.0           20.0    100.0  28.4   
240            1     91.0           64.0           24.0    155.0  29.2   
170            6    102.0           82.0           29.0    155.0  30.8   
691           13    158.0          114.0           29.0    155.0  42.3   
490            2     83.0           65.0           28.0     66.0  36.8   
45             0    180.0           66.0           39.0    155.0  42.0   
..           ...      ...            ...            ...      ...   ...   
448            0    104.0           64.0           37.0     64.0  33.6   
431            3     89.0           74.0           16.0     85.0  30.4   
709            2     93.0           64.0           32.0    160.0  38.0   
115            4    146.0           92.0           29.0    155.0  31.2   
72            13    126.0           90.0           29.0    155.0  43.4   
537            0     57.0           60.0           29.0    155.0  21.7   
677            0     93.0           60.0           29.0    155.0  35.3   
753            0    181.0           88.0           44.0    510.0  43.3   
174            2     75.0           64.0           24.0     55.0  29.7   
87             2    100.0           68.0           25.0     71.0  38.5   
551            3     84.0           68.0           30.0    106.0  31.9   
486            1    139.0           62.0           41.0    480.0  40.7   
705            6     80.0           80.0           36.0    155.0  39.8   
314            7    109.0           80.0           31.0    155.0  35.9   
396            3     96.0           56.0           34.0    115.0  24.7   
600            1    108.0           88.0           19.0    155.0  27.1   
472            0    119.0           66.0           27.0    155.0  38.8   
70             2    100.0           66.0           20.0     90.0  32.9   
599            1    109.0           38.0           18.0    120.0  23.1   
754            8    154.0           78.0           32.0    155.0  32.4   
277            0    104.0           64.0           23.0    116.0  27.8   
723            5    117.0           86.0           30.0    105.0  39.1   
9        

# perform feature scaling

In [76]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [77]:
X_train

array([[ 0.90832902,  0.93641795,  0.44764174, ...,  0.36863635,
         0.67740401,  1.69955804],
       [ 0.03644676, -0.81630913, -1.05200558, ..., -0.63294341,
        -0.07049698, -0.96569189],
       [-1.12606292,  1.43247278,  1.44740662, ...,  2.81535261,
        -0.11855487, -0.88240283],
       ..., 
       [ 0.03644676, -0.91552009, -0.63543688, ..., -1.13373329,
        -0.95656442, -1.04898095],
       [ 2.0708387 , -1.21315299,  0.11438678, ..., -0.36108605,
        -0.50001442,  0.11706589],
       [ 0.32707418,  0.47343344,  0.7808967 , ..., -0.08922869,
         0.52121586,  2.94889395]])

In [ ]:
# see above values are between 0 and 1

In [ ]:
# define the model init: k-nn

In [90]:
classifier = KNeighborsClassifier(n_neighbors = 100, p=2 , metric = 'euclidean')

In [91]:
import math
math.sqrt(len(y_test)) # here number is 12 and 12-1 is the number of neighbors

12.409673645990857

In [92]:
# now fit the model
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=100, p=2,
           weights='uniform')

In [93]:
# predict the test results
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [94]:
# evaluate model
cm = confusion_matrix(y_test , y_pred)
cm

array([[103,   4],
       [ 23,  24]], dtype=int64)

In [95]:
cm

array([[103,   4],
       [ 23,  24]], dtype=int64)

In [96]:
print(f1_score(y_test,y_pred))

0.64


In [97]:
print(accuracy_score(y_test,y_pred))

0.824675324675
