random forests are used for classification

In [ ]:
# source :
# https://www.youtube.com/watch?v=eM4uJ6XGnSM&list=PLEiEAq2VkUULYYgj13YHUWmRePqiu8Ddy&index=18

applications of random forests

In [ ]:
# 1. object detection
# 2. in remote sensing( used in etm devices to acquire the images from the earths surface)
# 3. used in kinect ( track the body moments and recreate in the game)

 advantages of random forests

1. no overfitting ( use of multiple trees reduce the chance of over fitting)
2. training time is less
3. high accuracy
4. run efficiently on large database
5. for large data it produce highly accurate results
6. estimates the missing data

 defination of random forest

  def : random forest or random decision forest is a method that operate by constructing multiple 
        decision trees during training phase
                       
                       and 
         
       the decision of the majority trees is chosen as the right decision by the random forest

# decision tree important terms:

entropy : entropy is the measure of randomness or unpredictability in the dataset

information gain : it is the measure of decrease in entropy after dataset is split

leaf node : leaf node carries the classification or decision

decision node : decision node has two or more branches

root node : the top most node is known as the root node

In [3]:
# import the dataset
from sklearn.datasets import load_iris
# load the random forest classifier
from sklearn.ensemble import RandomForestClassifier
# loadig pandas package
import pandas as pd
#loading numpy package
import numpy as np
# seeting random seed
np.random.seed(0)

In [6]:
# creating an object called iris with the iris data
iris = load_iris()
# creating a dataframe with the 4 feature variables
df = pd.DataFrame(iris.data , columns = iris.feature_names)
# viewing the top 5 rows
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
# adding a new column for the species name
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)
# viewing the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
len(df)

150

In [9]:
# creating test and train data
df['is_train'] = np.random.uniform(0,1,len(df)) <= .75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [10]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  is_train  
145  virginica      True  
146  virginica      True  
147  virginica     False  
148  virginica      True  
149  virginica     False

In [12]:
# creaing dataframes with test rows and train rows
train , test = df[df['is_train'] == True],df[df['is_train'] == False]
print('number of observations in the training data',len(train))
print('number of observations in the testing data',len(test))

number of observations in the training data 118
number of observations in the testing data 32


In [13]:
# create a list of feature columns names
features = df.columns[:4]
# view features
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [15]:
# convert each species names into digits
y= pd.factorize(train['species'])[0]
# viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2], dtype=int64)

In [17]:
# create a random forest classifier
clf = RandomForestClassifier(n_jobs = 2 ,random_state = 0)
# training the classifier
clf.fit(train[features],y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [18]:
# applying the testing data to the classifier
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [21]:
# viewing the predicted probabilities of first 10 features
clf.predict_proba(test[features])[0:20]

array([[ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.9,  0.1,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.9,  0.1,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.9,  0.1],
       [ 0. ,  0.2,  0.8],
       [ 0. ,  0.3,  0.7],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.8,  0.2]])

In [24]:
# maping names for the plants for each predicted class
pred = iris.target_names[clf.predict(test[features])]
pred[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'],
      dtype='<U10')

In [23]:
# viewing actual species names
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

# creating confusion matrix

In [25]:
pd.crosstab(test['species'],pred,rownames = ['Actual Species'],colnames = ['predicted species'])

predicted species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [ ]:
# if we see diagonally number of accurate predictions = 30
# number of inaccurate predictions = 2
# model accuracy = 30/32 * 100 = 93%

In [26]:
30/32 % 100

0.9375

In [28]:
pred = iris.target_names[clf.predict([[6.0,1.2,3.5,7.0],[2.2,4.5,6.7,1.1]])]

In [29]:
pred

array(['versicolor', 'virginica'],
      dtype='<U10')